name: Deploy Theme
on:
  push:
    branches:
      - master
jobs:
  deploy:
     runs-on: ubuntu-18.04
     steps:
       - uses: actions/checkout@master
       - name: Install Dependencies
         run: npm install
         working-directory: ./src
       - name: Build and Deploy Theme
         env:
           NODE_TLS_REJECT_UNAUTHORIZED: 0 # Ignore SSL errors; current certs are not chained properly
           GHOST_ADMIN_API_URL: ${{ secrets.GHOST_ADMIN_API_URL }}
           GHOST_ADMIN_API_KEY: ${{ secrets.GHOST_ADMIN_API_KEY }}
         run: npm run deploy
         working-directory: ./src
